# GitHub actions
# https://docs.github.com/en/free-pro-team@latest/actions

name: ci-test

on: [push, pull_request]
name: ci-test

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v3

    - name: setup Node.js v${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: run npm scripts
      env:
        PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
      run: |
        npm install
        npm run lint
        npm run build --if-present
        npm run test

    - name: Report Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
