# GitHub actions
# https://docs.github.com/en/free-pro-team@latest/actions

name: ci-test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20.x, 22.x, 23.x]

    steps:
    - uses: actions/checkout@v4

    - name: setup Node.js v${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: run npm scripts
      env:
        PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
      run: |
        npm install
        npm run lint
        npm run build --if-present
        npm run test

    - name: cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
